In [1]:
!mkdir -p ~/.kaggle/
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [2]:
!kaggle competitions download -c sejong-ai-challenge-p2

  0% 0.00/720k [00:00<?, ?B/s]
100% 720k/720k [00:00<00:00, 47.5MB/s]
 43% 9.00M/20.7M [00:00<00:00, 17.0MB/s]
100% 20.7M/20.7M [00:00<00:00, 30.3MB/s]
100% 8.87M/8.87M [00:00<00:00, 39.2MB/s]



In [3]:
!unzip test.csv.zip
!unzip train.csv.zip

Archive:  test.csv.zip
  inflating: test.csv                
Archive:  train.csv.zip
  inflating: train.csv               


In [4]:
import pandas as pd
import numpy as np

train = pd.read_csv("train.csv")
train = train.dropna()
train

Unnamed: 0                                               Text  Label
0           252571  Great price and quick service, the product is ...      1
1           216109  I just purchased the Samsung Galaxy Note 3 fro...      0
2            79523  DO NOT BUY THE CHARGER IS NOT A FAST CHARGING ...      0
3           231236  This is phone is not worth the price. This pho...      0
4           157402  Doesn't lay flat on the screen. Put it on in t...      0
...            ...                                                ...    ...
194135      119879  Very good, rapid charge great price would reco...      1
194136      259178                                   Great Product!!!      1
194137      131932  Broke two weeks after I started using it, not ...      0
194138      146867  Far and away the best case I've had for this p...      1
194139      121958  I am amazed and thrilled with this battery. I ...      1

[194139 rows x 3 columns]

In [5]:
train_x = train.loc[:, "Text"]
train_y = train.loc[:, "Label"]
train_y

0         1
1         0
2         0
3         0
4         0
         ..
194135    1
194136    1
194137    0
194138    1
194139    1
Name: Label, Length: 194139, dtype: int64

In [11]:
test = pd.read_csv("test.csv")
test_x = test.loc[:, "Text"]

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
train_x_tfidf = tfidf.fit_transform(train_x)
print(tfidf.get_feature_names())

['00', '000', '0000', '000000', '0000000', '00000000000000001', '000000000001', '00001', '0000mah', '000amp', '000ma', '000mah', '000s', '001', '0024', '003', '003395', '00393701', '004', '005v', '007', '009', '0090', '00a', '00am', '00mah', '00mg', '00pm', '00r_mpap', '00usd', '00x2', '01', '012117', '0155379', '016g', '016sxskpvis', '017', '01b6cymhgrs', '01bmcjjz', '01but', '01fhslqo9ss', '01gad7kzbxs', '01gsnrxqtus', '01rw1u6mzqs', '01uel', '01w', '01y', '02', '02212018', '024x1', '025', '02732f6', '02732q6', '0280', '029', '02mbps', '02nd', '03', '032', '032_b50', '037', '03a', '03cm', '03mm', '03v', '04', '0403532', '041cs20168', '041fl20165', '0430', '0445', '04a', '04pm', '04v', '05', '050', '0500', '050q', '05122017', '0520', '0597014925', '05a', '05mm', '05p', '05v', '06', '0600', '06015', '06072012', '0611set', '0621', '0621a', '06272012', '0630', '064g', '06a', '06a2f3c5ca', '06am', '07', '0700', '074', '0766', '077', '07in', '07mpixel', '08', '084', '08mbps', '09', '0900',

In [14]:
test_x_tfidf = tfidf.transform(test_x)
print(tfidf.get_feature_names())

['00', '000', '0000', '000000', '0000000', '00000000000000001', '000000000001', '00001', '0000mah', '000amp', '000ma', '000mah', '000s', '001', '0024', '003', '003395', '00393701', '004', '005v', '007', '009', '0090', '00a', '00am', '00mah', '00mg', '00pm', '00r_mpap', '00usd', '00x2', '01', '012117', '0155379', '016g', '016sxskpvis', '017', '01b6cymhgrs', '01bmcjjz', '01but', '01fhslqo9ss', '01gad7kzbxs', '01gsnrxqtus', '01rw1u6mzqs', '01uel', '01w', '01y', '02', '02212018', '024x1', '025', '02732f6', '02732q6', '0280', '029', '02mbps', '02nd', '03', '032', '032_b50', '037', '03a', '03cm', '03mm', '03v', '04', '0403532', '041cs20168', '041fl20165', '0430', '0445', '04a', '04pm', '04v', '05', '050', '0500', '050q', '05122017', '0520', '0597014925', '05a', '05mm', '05p', '05v', '06', '0600', '06015', '06072012', '0611set', '0621', '0621a', '06272012', '0630', '064g', '06a', '06a2f3c5ca', '06am', '07', '0700', '074', '0766', '077', '07in', '07mpixel', '08', '084', '08mbps', '09', '0900',

In [28]:
from sklearn import linear_model, model_selection
clf = linear_model.RidgeClassifier()

scores = model_selection.cross_val_score(clf, train_x_tfidf, train_y , cv=5, scoring="f1")
scores

array([0.90116339, 0.90248356, 0.90156384, 0.90205958, 0.90120244])

In [29]:
clf.fit(train_x_tfidf, train_y)

RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, normalize=False, random_state=None,
                solver='auto', tol=0.001)

In [30]:
train_pred_y = clf.predict(train_x_tfidf)

In [31]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(train_y, train_pred_y))

[[90823  6369]
 [ 7764 89183]]


In [15]:
test_pred_y = clf.predict(test_x_tfidf)
test_pred_y

array([1, 0, 0, ..., 0, 0, 1])

In [21]:
test_pred_y[5]

0

In [17]:
sample_submission = pd.read_csv("sample_submission.csv")
sample_submission["Label"] = test_pred_y

In [18]:
sample_submission.head()

id  Label
0   0      1
1   1      0
2   2      0
3   3      0
4   4      0

In [22]:
sample_submission.to_csv("submission.csv", index=False)

In [23]:
!kaggle competitions submit -c sejong-ai-challenge-p2 -f submission.csv -m "first"

100% 639k/639k [00:02<00:00, 309kB/s]
Traceback (most recent call last):
  File "/usr/local/bin/kaggle", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/kaggle/cli.py", line 64, in main
    print(out, end='')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 46-47: ordinal not in range(256)
